# Generated by Django 3.2 on 2021-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yqlabModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Lab Register No', models.CharField(max_length=100)),
                ('Plant', models.CharField(max_length=100, null=True)),
                ('Material', models.CharField(max_length=100)),
                ('Material Description', models.CharField(max_length=100)),
                ('Sample Drawn By', models.CharField(max_length=100)),
                ('Sample Drawn Date', models.CharField(max_length=100)),
                ('Source of Sample', models.CharField(max_length=100, null=True)),
                ('Name of Source', models.CharField(max_length=100, null=True)),
                ('Storage Tank', models.CharField(max_length=100)),
                ('Sample Type', models.CharField(max_length=100, null=True)),
                ('Qty in Storage (KL)', models.CharField(max_length=100, null=True)),
                ('Batch', models.CharField(max_length=100, null=True)),
                ('Test Required', models.CharField(max_length=100, null=True)),
                ('Test Reason', models.CharField(max_length=100, null=True)),
                ('Observed Density', models.CharField(max_length=100, null=True)),
                ('Last Receipt Date', models.CharField(max_length=100, null=True)),
                ('Dispatching Location Test Report No', models.CharField(max_length=100, null=True)),
                ('SKO Flash Point', models.CharField(max_length=100, null=True)),
                ('Created By', models.CharField(max_length=100, null=True)),
                ('Created On', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Inspection Lot', models.CharField(max_length=100, null=True)),
                ('Remarks', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'yqlab',
            },
        ),
        migrations.CreateModel(
            name='yvrokarModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Material', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100, null=True)),
                ('Tank', models.CharField(max_length=100)),
                ('Tank Status', models.CharField(max_length=100, null=True)),
                ('Opening Dip', models.CharField(max_length=100, null=True)),
                ('Waterdip', models.CharField(max_length=100, null=True)),
                ('Temperature', models.CharField(max_length=100, null=True)),
                ('Quantity', models.CharField(max_length=100, null=True)),
                ('Receipt', models.CharField(max_length=100, null=True)),
                ('Issue', models.CharField(max_length=100, null=True)),
                ('Book Balance', models.CharField(max_length=100, null=True)),
                ('Closing Dip', models.CharField(max_length=100, null=True)),
                ('Waterdip1', models.CharField(max_length=100, null=True)),
                ('Temperature1', models.CharField(max_length=100, null=True)),
                ('Physical Balance', models.CharField(max_length=100, null=True)),
                ('Loss/Gain', models.CharField(max_length=100, null=True)),
                ('Remarks', models.CharField(max_length=100, null=True)),
                ('QtyDiff', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'yvrokar',
            },
        ),
    ]
