# Generated by Django 3.2 on 2021-05-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yqlabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S.No.', models.CharField(max_length=100)),
                ('Lab Register No.', models.CharField(max_length=100)),
                ('Plant', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('Material Description', models.CharField(max_length=100)),
                ('Sample Drawn By', models.CharField(max_length=100)),
                ('Sample Drawn Date', models.CharField(max_length=100)),
                ('Sample Drawn Time', models.CharField(max_length=100)),
                ('Source of Sample', models.CharField(max_length=100)),
                ('Name of Source', models.CharField(max_length=100)),
                ('Storage Tank', models.CharField(max_length=100)),
                ('Sample Type', models.CharField(max_length=100)),
                ('Qty. of Sample (L)', models.CharField(max_length=100)),
                ('Qty. in Storage (KL)', models.CharField(max_length=100)),
                ('No. of Containers', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
                ('Test Required', models.CharField(max_length=100)),
                ('Test Reason', models.CharField(max_length=100)),
                ('Invoice/Code No.', models.CharField(max_length=100)),
                ('Retail Outlet Name', models.CharField(max_length=100)),
                ('Oil Company Name', models.CharField(max_length=100)),
                ('Supplying Plant', models.CharField(max_length=100)),
                ('Tank Lorry No.', models.CharField(max_length=100)),
                ('RO Tank No.', models.CharField(max_length=100)),
                ('RO Dispensing Unit', models.CharField(max_length=100)),
                ('Recorded Density', models.CharField(max_length=100)),
                ('Observed Density', models.CharField(max_length=100)),
                ('Last Receipt Date', models.CharField(max_length=100)),
                ('Last Receipt TT No.', models.CharField(max_length=100)),
                ('Last Receipt Location', models.CharField(max_length=100)),
                ('Test Laboratory', models.CharField(max_length=100)),
                ('Dispatching Location Test Report No.', models.CharField(max_length=100)),
                ('SKO Flash Point', models.CharField(max_length=100)),
                ('Outer Seal No.', models.CharField(max_length=100)),
                ('Inner Seal No.', models.CharField(max_length=100)),
                ('Created By', models.CharField(max_length=100)),
                ('Created On', models.CharField(max_length=100)),
                ('Created At', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Inspection Lot', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'yqlab',
            },
        ),
        migrations.CreateModel(
            name='yvrokarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=100)),
                ('Unit', models.CharField(max_length=100)),
                ('Tank', models.CharField(max_length=100)),
                ('Tank Status', models.CharField(max_length=100)),
                ('Opening Dip', models.CharField(max_length=100)),
                ('Waterdip', models.CharField(max_length=100)),
                ('Temperature', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Receipt', models.CharField(max_length=100)),
                ('Issue', models.CharField(max_length=100)),
                ('Book Balance', models.CharField(max_length=100)),
                ('Closing Dip', models.CharField(max_length=100)),
                ('Waterdip.1', models.CharField(max_length=100)),
                ('Temperature.1', models.CharField(max_length=100)),
                ('Physical Balance', models.CharField(max_length=100)),
                ('Loss/Gain', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
                ('QtyDiff', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'yvrokar',
            },
        ),
    ]
