godryColumn=['SO NAME', 'DO NAME', 'SALES AREA', 'RO CODE', 'RO NAME', 'SUPPLY LOCATION', 'PRODUCT', 'NO. OF TANKS', 'TANKAGE', 'STOCK DATE/ TIME', 'STOCK AVAILABLE (L)', 'DEAD STOCK (L)', 'STOCK ON WHEEL AVAILABLE (L)', 'PENDING INDENT QUANTITY (L)', 'AVERAGE NOZZLE SALES (L)', 'INDENT EXECUTION TIME (HRS.)', 'TRANSIT TIME (HRS.)', 'STOCK SURVIVAL HOURS (HRS.)', 'EXPECTED DRYOUT DATE/ TIME', 'STATUS CRITICAL']
outofstockColumn=['SO NAME', 'DO NAME', 'SALES AREA', 'DATE', 'RO CODE', 'RO NAME', 'PRODUCT', 'NO. OF TANK', 'TOTAL HOURS STOCK OUT', 'POTENTIAL LOSS (IN LITERS)', 'STOCK OUT HOURS - CUR MONTH', 'POTENTIAL LOSS - CUR MONTH (IN LITERS)', 'STOCK OUT HOURS - PREVIOUS MONTH', 'POTENTIAL LOSS - PREVIOUS MONTH (IN LITERS)']
romobileColumn=['Mobile Number', 'Ship-To Party', 'Sales Office', 'Distribution Channel', 'Differ.Refer.Code', 'Mobile Type', 'Name 1', 'City', 'Description', 'Created By', 'Created On', 'Time', 'E-Mail Address']
rolistColumn=['Ship2Party', 'Name', 'SOff.', 'Rg']
yv26Column=['Rec. Code', 'Receiver', 'Document', 'Disp.Mat.Doc.', 'Disp.Item', 'Disp.St.Loc.', 'Recv.Mat.Doc.', 'Recv.Item', 'Recv.St.Loc.', 'PGI Date', 'Batch', 'Mat.Code', 'MoT', 'InvoiceNo.', 'Assign.No.', 'Volume(KL)', 'Volume(K15)', 'Volume(K29)', 'Volume(TO)', 'Qty(EA)', 'State']   
yv208Column=['Exception', 'Material', 'Shipment', 'Shp.Status', 'Vehicle', 'Ship2Party', 'Name', 'Delivery', 'Quantity', 'Sales Unit', 'Delivery quantity', 'Seal No.', 'Invoice']
yv209dColumn=['Exception', 'DelCt', 'PRTY', 'Requested deliv.date', 'Sales Document', 'Distribution Channel', 'Ship2Party', 'Name 1', 'RTD(in KM)', 'Material', 'OrderQty', 'Target quantity UoM', 'Truck no.', 'Sales Group Desc.', 'REMARKS', 'Sales Document Type', 'Sales Document Item', 'Created By', 'Sales Group']


Columns=[godryColumn,outofstockColumn,romobileColumn,rolistColumn,yv26Column,yv208Column,yv209dColumn]