# Generated by Django 3.2 on 2021-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'mytable',
            },
        ),
        migrations.CreateModel(
            name='godryModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeStamp', models.CharField(max_length=100, null=True)),
                ('ModifiedBy', models.CharField(max_length=100, null=True)),
                ('SO NAME', models.CharField(max_length=100, null=True)),
                ('DO NAME', models.CharField(max_length=100)),
                ('SALES AREA', models.CharField(max_length=100, null=True)),
                ('RO CODE', models.CharField(max_length=100)),
                ('RO NAME', models.CharField(max_length=100)),
                ('SUPPLY LOCATION', models.CharField(max_length=100, null=True)),
                ('PRODUCT', models.CharField(max_length=100)),
                ('NO OF TANKS', models.CharField(max_length=100, null=True)),
                ('TANKAGE', models.CharField(max_length=100, null=True)),
                ('STOCK DATE/ TIME', models.CharField(max_length=100, null=True)),
                ('STOCK AVAILABLE (L)', models.CharField(max_length=100, null=True)),
                ('DEAD STOCK (L)', models.CharField(max_length=100, null=True)),
                ('STOCK ON WHEEL AVAILABLE (L)', models.CharField(max_length=100, null=True)),
                ('PENDING INDENT QUANTITY (L)', models.CharField(max_length=100, null=True)),
                ('AVERAGE NOZZLE SALES (L)', models.CharField(max_length=100, null=True)),
                ('INDENT EXECUTION TIME (HRS)', models.CharField(max_length=100, null=True)),
                ('TRANSIT TIME (HRS)', models.CharField(max_length=100, null=True)),
                ('STOCK SURVIVAL HOURS (HRS)', models.CharField(max_length=100, null=True)),
                ('EXPECTED DRYOUT DATE/ TIME', models.DateTimeField(max_length=100)),
                ('STATUS CRITICAL', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'godry',
            },
        ),
        migrations.CreateModel(
            name='rolistModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeStamp', models.CharField(max_length=100, null=True)),
                ('ModifiedBy', models.CharField(max_length=100, null=True)),
                ('Ship2Party', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('SOff', models.CharField(max_length=100, null=True)),
                ('Rg', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'rolist',
            },
        ),
        migrations.CreateModel(
            name='yv26Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TimeStamp', models.CharField(max_length=100, null=True)),
                ('ModifiedBy', models.CharField(max_length=100, null=True)),
                ('Rec Code', models.CharField(max_length=100)),
                ('Receiver', models.CharField(max_length=100)),
                ('Document', models.CharField(max_length=100, null=True)),
                ('DispMatDoc', models.CharField(max_length=100, null=True)),
                ('DispItem', models.CharField(max_length=100, null=True)),
                ('DispStLoc', models.CharField(max_length=100, null=True)),
                ('RecvMatDoc', models.CharField(max_length=100, null=True)),
                ('RecvItem', models.CharField(max_length=100, null=True)),
                ('RecvStLoc', models.CharField(max_length=100, null=True)),
                ('PGI Date', models.DateTimeField(max_length=100)),
                ('Batch', models.CharField(max_length=100, null=True)),
                ('MatCode', models.CharField(max_length=100)),
                ('MoT', models.CharField(max_length=100, null=True)),
                ('InvoiceNo', models.CharField(max_length=100)),
                ('AssignNo', models.CharField(max_length=100, null=True)),
                ('Volume(KL)', models.CharField(max_length=100)),
                ('Volume(K15)', models.CharField(max_length=100, null=True)),
                ('Volume(K29)', models.CharField(max_length=100, null=True)),
                ('Volume(TO)', models.CharField(max_length=100, null=True)),
                ('Qty(EA)', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'yv26',
            },
        ),
    ]
