# Generated by Django 3.2 on 2021-06-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'mytable',
            },
        ),
    ]
