# Generated by Django 3.2 on 2021-05-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yv208',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=100, null=True)),
                ('Shipment', models.CharField(max_length=100, null=True)),
                ('Vehicle', models.CharField(max_length=100, null=True)),
                ('Ship2Party', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Delivery', models.CharField(max_length=100, null=True)),
                ('Quantity', models.CharField(max_length=100, null=True)),
                ('Invoice', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
