# Generated by Django 3.2 on 2021-05-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yv208',
        ),
    ]
